name: Build Docker Image
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code

      uses: actions/checkout@v3

    - name: Build & push Docker image

      uses: mr-smithers-excellent/docker-build-push@v6
      
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

      with:

        image: enricopierocosta/dockerenricoactions

        tags: v${{ steps.version.outputs.version }}

        registry: docker.io

        dockerfile: dockerfile

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}

